# Generated by Django 5.2.3 on 2025-07-09 07:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_review_user_review_name_review_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
