# Generated by Django 5.2.3 on 2025-06-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_star_remove_review_rating_review_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['-star']},
        ),
        migrations.RenameField(
            model_name='star',
            old_name='value',
            new_name='star',
        ),
    ]
