# Generated by Django 5.2.3 on 2025-06-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_attribute_product_remove_attribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attribute',
            name='value',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
