# Generated by Django 5.2.3 on 2025-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_star_options_rename_value_star_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
