# Generated by Django 5.2.3 on 2025-07-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_base_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='default_price',
        ),
    ]
