# Generated by Django 5.2.3 on 2025-07-20 10:26

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_base_price_product_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail2',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Thumbnail'),
        ),
    ]
