# Generated by Django 5.2.3 on 2025-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_variant_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('paid', 'Đã thanh toán'), ('shipped', 'Đã giao hàng'), ('delivered', 'Đã nhận hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
