# Generated by Django 5.2.3 on 2025-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_images_productvariant_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
