# Generated by Django 5.2.3 on 2025-07-20 10:36

import filebrowser.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_thumbnail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Image'),
        ),
    ]
