# Generated by Django 5.2.3 on 2025-06-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_attribute_remove_productvariant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.image'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
