# Generated by Django 5.2.3 on 2025-07-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_thumbnail3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail3',
        ),
    ]
