# Generated by Django 5.2.3 on 2025-07-20 11:54

import store.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_thumbnail3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=store.fields.MediaGridManyToManyField(blank=True, related_name='images', to='store.image'),
        ),
    ]
